### PR TITLE
Add Gradle as a build system

### PR DESCRIPTION
**Pull request by robertsmieja**
Includes #53 

Converts the project to use Gradle (http://gradle.org/), and includes the Gradle wrapper which allows building using `./gradlew build`

If you would not like this change, I am ok with keeping it local to my machine.

My personal opinion is that Gradle is the best build system so far, and does everything that Maven does and more. I have not deleted the pom.xml for Maven.

### CODE REVIEW

**Comment by spheenik** [comment]
Hey,

thx, but I don't want to change the build system, I seem to like maven.
I don't really know what using gradle will accomplish?

Also, I can't switch, since the management of deployment to Sonatype and Maven Central is all done by a maven profile...

**Comment by robertsmieja** [comment]
I don't want to preach, but I think Gradle is just the best build system.

It can do everything Maven can, and the build.gradle file is more readable than Maven's pom.xml. The build.gradle for this project can be seen here: https://github.com/robertsmieja/clarity/blob/1d8f51b824911b11ccc9dcd915a0db3409a0858f/build.gradle

By Sonatype do you mean Sonatype Nexus? Gradle has support for publishing to Maven: https://docs.gradle.org/current/userguide/publishing_maven.html

If you're interested I'd be happy to help, but if you're not, I won't press the issue. It's your project after all. :)

**Comment by ChrisE87** [comment]
I have to work with gradle every day and I still don't understand what the hype is about, even so far that it is getting to a point where people pressure developers to change it. 

Yes, it is more readable than a pom, but in most cases projects don't do much more than adding dependencies. In exchange, I feel like half the developing time is now waiting for the build to finish. I'm losing so much development time with that in bigger projects, it's ridiculous. Almost everyone I know curses it when coming from Maven.

**Comment by robertsmieja** [comment]
That doesn't seem right. At my job, it cut down nightly build times in half. It also provides the Gradle Wrapper so new contributors don't have to configure or install Maven, and can run the gradlew.bat or gradlew scripts.

It's target audience is medium or larger enterprise projects, but it also works well for simple projects as it takes care of the default configurations, since a simple build file for a Java project is ten lines or less. 

Like I said, I won't press the issue, but I'm more than happy to more to help if @spheenik wants to give it a try.

**Comment by spheenik** [comment]
Hi,
for me, gradle is ant in disguise. 
You can do whatever the fuck you want with your buildscript. This is exactly why I wont switch to it.

I WANT a standard process that my IDE can understand.

Atm, I am in a project where they build a Java EE application with gradle. Of course, the IDE does not understand build.gradle completely, so you manually have to click around to have some libraries in ear/lib.

 I come from hell with buggy ant scripts, and while I agree that the pom is verbose because of XML, I prefer it. 

For example: I am working on clarity in Intellij. I find out I wanna work on the protobufs, so I temporarily add clarity-protobuf as a module. IDE knows without a click that clarity-protobuf is a dependency from clarity, and will build (and deploy) any changes to -protobuf first. When I am finished, I mvn deploy once in clarity-protobuf, so the jar is in my local maven repo, remove the module, done. Everything is just integrated so nicely.

Also: I don't only need to do maven-deploy, I need to deploy to sonatype-oss. Atm, this works with a single click from the IDE for snapshots (mvn deploy) or two if I wanna relase (check release profile, mvn deploy).

If I take your gradle script, I have a nicely looking script, but all this is gone.
To get it back, I'd need to http://jedicoder.blogspot.de/2011/11/automated-gradle-project-deployment-to.html 

Here is an example build.gradle that accomplishes that: https://github.com/GradleFx/GradleFx/blob/develop/build.gradle (120 SLOC).

My pom.xml does that in 70 SLOC: https://github.com/skadistats/clarity/blob/master/pom.xml

So much for verbosity...

Nope, don't wanna change.

**Pull request closed without merging**
